### ISSUE TITLE
Current Relative Humidity is undefined

### ISSUE THREAD

**Issue by lanebrain** [jxg81/homebridge-actron-que#1]
The Que Zone sensors don't seem to support humidity readings.  So would be good to be able to toggle this ability off so they don't appear in the home app.

Also the logs keep getting filled up with the following event - [homebridge-actron-que] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

I just got the Que setup last night. Configuring this plugin was super easy.  Keep up the great work and thanks!

**Comment by jxg81** [comment]
hey @lanebrain - thanks for the feedback.
Interesting that your zone sensors don't report humidity. I have only had my system to test against (which is using zone sensors that do report humidity) so would be great to get a look at the api response for your AC system status.

Would you be able to do the following:
- Browse to `https://que.actronair.com.au` and login to your account
- Once logged in, go to 'View AC Systems' and get the serial no. of your ac system
- Open a new tab and browse to:
`https://que.actronair.com.au/api/v0/client/ac-systems/status/latest?serial=<your_serial_number>`
  - For example, if you serial number is 'abc123' the URL would be formatted as:
`https://que.actronair.com.au/api/v0/client/ac-systems/status/latest?serial=abc123`
- Post the JSON response in its entirety here for me to review

This will help determine the differences in your system and update the code to accomodate the variations.
This JSON data itself does not contain any particularly sensitive information - the only individual or potentially identifiable information is the timezone and serial number data in the output, but if you would rather send privately let me know and we can exchange through a different channel.

**Comment by lanebrain** [comment]
Hey Julian,

JSON is below.  I do get humidity from the main controller, I don’t have the zone controllers, just the zone sensors - https://actronair.com.au/controls/que/ <https://actronair.com.au/controls/que/>

Cheers!

{"isOnline":true,"timeSinceLastContact":"00:00:35.4061347","lastStatusUpdate":"2022-08-05T04:32:50+00:00","lastKnownState":{"<22G04505>":{"Cloud":{"ConnectionState":"Connected","FailedSentPackets":2,"ReceivedPackets":221,"SentPackets":1698},"Modbus":{"LinkPort":"Opened"},"NV_SystemSettings_Local":{"Screen":{"AutoWake":true,"BrightnessAuto":true,"Brightness_pc":80,"Timeout_sec":300},"ScreenOffDisabled":false,"Sounds":{"Mute":true,"Volume_pc":50},"amMasterController":true,"isConfigured":true,"isLinkedToCloud":true,"scheduledRebootEnabled":false},"NV_Updates":{"WCUpdateRefusedVersion":"","ZCUpdateRefusedVersion":""},"SystemState":{"CpuFreq_MHz":996,"CpuId":"0xd57ea01d91d29d4","CpuLoad_User":39,"CpuRev":"1.5\n","CpuTempMax_oC":32,"CpuTemp_oC":30.95,"LastBootWasSafe":false,"LastShutdownReason":"Unknown","LinkedToMaster":false,"MemUsage_K":284000,"NV_LastBootFromUnsafeUTC":"2022-08-04 21:40:37","NV_UnsafeShutdowns":3,"ScreenIsOn":false,"SystemUptime_s":83258.15,"WCFirmwareVersion":"1.418.1.569","ZCFirmwareVersion":"31","hasInternet":true},"SystemStatus_Local":{"ConnectedToFallBackWifi":false,"LastScreenTouch_UTC":"2022-08-04 23:59:25","NTC1Temp_oC":25.4,"NTC2Temp_oC":30.8,"NV_TemperatureOffset":0,"SHTHumidity_oC":42.5,"SHTTemp_oC":25,"ScreenInactive":true,"ScreenLocked":false,"Temp_ScreenOffMode":"Normal","TemperatureForUse_oC":22,"WifiStrength_of3":3}},"ACStats":{"NV_FanRunTime_10m":29,"NV_FanRunTime_Total_10m":29},"AirconSystem":{"IndoorUnit":{"DeviceID_Changed":false,"IndoorFW":115,"NV_DeviceID":"ERQ2-14","NV_ModelNumber":140,"ZoneDetectRun":true},"MasterSerial":"22G04505","OutdoorUnit":{"AOCSoftwareVersion":277,"HardwareVersion":1,"MOCSoftwareHardwareVersion":277,"ModBusAddr":1,"Model":0,"ModelNumber":561,"SoftwareVersion":107}},"Alerts":{"CleanFilter":false,"DRED":false,"Defrosting":false},"LiveAircon":{"AmRunningFan":false,"CanRunSystem":true,"CoilInlet":25,"CompressorCanRun":true,"CompressorCapacity":0,"CompressorChasingTemperature":21,"CompressorLiveTemperature":23.15,"CompressorMode":"HEAT","DRM":false,"Defrost":false,"DraftRecutionInfo":"","ErrCode":0,"FanDemandPC":0,"FanPWM":0,"FanRPM":0,"IndoorUnitTemp":27.0366222142448,"LastCompressorPowerChange":"13044938","LastCompressorPowerChange_time":"2022-08-05 11:18:02","ModbusErr":0,"OutdoorUnit":{"AmbTemp":19,"AmbientSensErr":false,"AutoMode":1,"CoilSenseErr":false,"CoilTemp":20.2,"CompMustRunOFF":false,"CompMustRunON":false,"CompPower":0,"CompRunningPWM":0,"CompSpeed":0,"CompressorMode":2,"CompressorOn":false,"CompressorSetSpeed":0,"CondPc":13.891440391540527,"ContFan":false,"DRM":0,"DRMModeTime_s":0,"DeIceConfirm_s":0,"DeIceHoldMax_s":1800,"DeIceHold_s":1800,"DeIceTime_s":0,"DefrostCycleNo":0,"DefrostMode":1,"DischargeTemp":21.948371887207031,"DriveAOCVersion":277,"DriveDefault":false,"DriveHP2":false,"DriveMOCVersion":277,"DriveTemp":0,"ECFanErr":false,"EEV":{"ControlStatus":0,"EvapPress":-800,"EvapTemp":20.7,"Opening_pc":30,"S2Temp":24.2,"S4AirTemp":120,"SuperHeat":3.5,"SuperHeatRef":2},"EXV":true,"EXVErr":false,"ErrCode_1":26,"ErrCode_2":26,"ErrCode_3":26,"ErrCode_4":15,"ErrCode_5":5,"ErrFlag":0,"EvacMode":false,"FanMode":0,"FanSetSpeed":40,"FanSpeed":0,"Fault":false,"ForcedDefrost":false,"HPErr":false,"HPLPTripTime_s":0,"HPTripCount":0,"IndoorEEVTemp":0,"LPBypass_s":0,"LPErr":false,"LPTripCount":68,"Mode":2,"ODFan":0,"ODUDefault":false,"ODUSel":0,"OilReturn":false,"OilReturnEnable":true,"RemoteOnOff":false,"RevTimeout_s":0,"RevTimoutOn":false,"RevValue":true,"RoomTemp":20,"RoomTempODU":20,"RoomTempSet":20,"SFanErr":false,"ServiceStatusCodes":"HP0","SetTempODU":20,"SuctP0":13.839939117431641,"SuctTemp":19,"SuctionSensErr":false,"SupplyPhaseA_Current":0.2,"SupplyPhaseB_Current":0.1,"SupplyPhaseC_Current":0,"SupplyVolatge_Vac":226,"TestModeCooling":false,"TestModeHeating":false},"SensorErr":0,"SystemOn":false,"TestCycle":"None","ZoneDemandSufficient":true,"isAntiFreeze":false},"MasterInfo":{"CloudConnected":"Connected","CloudReachable":true,"ControlAllZones":false,"LiveHumidity_pc":42.5,"LiveOutdoorTemp_oC":19,"LiveTempHysteresis_oC":23,"LiveTemp_oC":23.15,"RemoteHumidity_pc":{"22G04505":42.5},"Sensors":{"22G04505":{"Signal_of3":0}}},"NV_Limits":{"UserSetpoint_oC":{"MinGap":2,"VarianceAboveMasterCool":2,"VarianceAboveMasterHeat":2,"VarianceBelowMasterCool":-2,"VarianceBelowMasterHeat":-2,"setCool_Max":32,"setCool_Min":20,"setHeat_Max":26,"setHeat_Min":10}},"NV_QuickTimer":{"Master":[{"OriginalTime":"1:25","Status":"Stopped","Time":"55:55:55","Zones":[true,true,true,true,true,true,true,true]},{"OriginalTime":"1:00","Status":"Stopped","Time":"55:55:55","Zones":[true,true,true,true,true,true,true,true]}],"Zone":[[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}],[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}],[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}],[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}],[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}],[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}],[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}],[{"Status":"Stopped","Time":"55:55:55","ZoneState":true},{"Status":"Stopped","Time":"55:55:55","ZoneState":false}]]},"NV_Schedule":{"Enabled":false},"NV_SystemSettings":{"AFP_ChaseTemp_oC":8,"AFP_ExitTemp_oC":15,"AFP_StartTemp_oC":5,"AwayMode":{"TemperatureSetpoint_Cool_oC":26,"TemperatureSetpoint_Heat_oC":16},"ControlAircon":{"CompressorLoopTime_s":30,"CompressorModeAutoSwitchTimeNonVAV_m":0,"CompressorModeAutoSwitchTimeVAV_m":20,"CompressorPowerSwitchTime_m":3,"Ki":"jwUJzUjTBrUTsqwxP+xqYw==","Kp":"jwUJzUjTBrUTsqwxP+xqY74=","VAVThreshold":40},"DebugEnabled":false,"DebugLoggingEnabled":false,"DraftReductionEnabled":false,"EnergyHistory":{"Interval_min":15,"Max_oC":40,"Min_oC":0},"Lock":{"Enabled":false,"Passcode":""},"Logs":{"errLogDuration_days":7,"modBusLogDuration_days":7,"snapshotDebounce_ms":30000,"snapshotLogDuration_days":7,"snapshotTime_ms":900000},"MaxSecondaryControllers":1,"PingPeriod_min":60,"PingUrl":"http://lx-cloud.com/cloud_activity/mark_event/","RFNetworkAddress":[120,140,199,126,227,49],"SystemName":"ActronAir","SystemSetup":{"MaxCoolCompCapacity":100,"MaxHeatCompCapacity":100,"MaxSLFanSpeed":1416,"SectionsAttempted":[true,true,true,true,true],"SetupComplete":true,"SetupSectionsPassed":[null,null,null,null,null,true],"TestStatus":["Pass","Pass","Pass"]},"Time":{"SetAutomatically":true,"TimeMode24h":true,"Timezone":"Australia/NSW","Timezone_Readable":"NSW, Australia"},"UpdateTime":"55:55","UserACSettings":{"DefrostFanPWM":10,"FanAlertTime_h":1000,"Fanspeed":{"High":81,"HighDefault":81,"HighRPM":1500,"Low":35,"LowDefault":35,"LowRPM":1150,"Med":52,"MedDefault":52,"MedRPM":1290}},"WebUrl":"https://que.actronair.com.au/api/v0","enableFastHeat":false,"restoreSettingsOnPowerUp":true},"NV_Updates":{"LastUpdateCheck":"05/08/2022 07:41:28"},"RemoteZoneInfo":[{"CanOperate":true,"LiveTempHysteresis_oC":23,"LiveTemp_oC":23.1,"MaxCoolSetpoint":25,"MaxHeatSetpoint":23,"MinCoolSetpoint":21,"MinHeatSetpoint":19,"NV_Exists":true,"NV_Title":"Living Room","NV_VAV":true,"NV_amSetup":true,"RemoteTemperatures_oC":{"22G05161":23.1},"Sensors":{"22G05161":{"Battery_pc":60,"Connected":true,"NV_Kind":"SENSOR","NV_isPaired":true,"NV_isViaRepeater":false,"Signal_of3":3,"TX_Power":12,"lastRssi":-83}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0},{"CanOperate":true,"LiveTempHysteresis_oC":25.5,"LiveTemp_oC":25.5,"MaxCoolSetpoint":25,"MaxHeatSetpoint":23,"MinCoolSetpoint":21,"MinHeatSetpoint":19,"NV_Exists":true,"NV_Title":"Main Bedroom","NV_VAV":true,"NV_amSetup":true,"RemoteTemperatures_oC":{"22G05170":25.5},"Sensors":{"22G05170":{"Battery_pc":60,"Connected":true,"NV_Kind":"SENSOR","NV_isPaired":true,"NV_isViaRepeater":false,"Signal_of3":3,"TX_Power":27,"lastRssi":-83}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0},{"CanOperate":true,"LiveTempHysteresis_oC":21.5,"LiveTemp_oC":21.8,"MaxCoolSetpoint":25,"MaxHeatSetpoint":23,"MinCoolSetpoint":21,"MinHeatSetpoint":19,"NV_Exists":true,"NV_Title":"TV Room","NV_VAV":true,"NV_amSetup":true,"RemoteTemperatures_oC":{"22G05174":21.8},"Sensors":{"22G05174":{"Battery_pc":50,"Connected":true,"NV_Kind":"SENSOR","NV_isPaired":true,"NV_isViaRepeater":false,"Signal_of3":3,"TX_Power":9,"lastRssi":-56}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0},{"CanOperate":true,"LiveTempHysteresis_oC":23,"LiveTemp_oC":23.1,"MaxCoolSetpoint":25,"MaxHeatSetpoint":23,"MinCoolSetpoint":21,"MinHeatSetpoint":19,"NV_Exists":true,"NV_Title":"Guest Bedroom","NV_VAV":true,"NV_amSetup":true,"RemoteTemperatures_oC":{"22G05171":23.1},"Sensors":{"22G05171":{"Battery_pc":60,"Connected":true,"NV_Kind":"SENSOR","NV_isPaired":true,"NV_isViaRepeater":false,"Signal_of3":3,"TX_Power":9,"lastRssi":-59}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0},{"CanOperate":true,"LiveTempHysteresis_oC":22,"LiveTemp_oC":22.2,"MaxCoolSetpoint":25,"MaxHeatSetpoint":23,"MinCoolSetpoint":21,"MinHeatSetpoint":19,"NV_Exists":true,"NV_Title":"Office","NV_VAV":true,"NV_amSetup":true,"RemoteTemperatures_oC":{"22G05162":22.2},"Sensors":{"22G05162":{"Battery_pc":60,"Connected":true,"NV_Kind":"SENSOR","NV_isPaired":true,"NV_isViaRepeater":false,"Signal_of3":3,"TX_Power":9,"lastRssi":-75}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0},{"LiveTemp_oC":25,"NV_Exists":false,"NV_Title":"","NV_VAV":false,"Sensors":{"INVALID:C8:DF:84:45:42:C3":{"NV_Kind":"MASTER_CONTROLLER","NV_isPaired":true,"NV_isViaRepeater":false}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0},{"LiveTemp_oC":25,"NV_Exists":false,"NV_Title":"","NV_VAV":false,"Sensors":{"INVALID:C8:DF:84:45:42:C3":{"NV_Kind":"MASTER_CONTROLLER","NV_isPaired":true,"NV_isViaRepeater":false}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0},{"LiveTemp_oC":25,"NV_Exists":false,"NV_Title":"","NV_VAV":false,"Sensors":{"INVALID:C8:DF:84:45:42:C3":{"NV_Kind":"MASTER_CONTROLLER","NV_isPaired":true,"NV_isViaRepeater":false}},"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"ZonePosition":0}],"Servicing":{"FortnightZoneDetection":{"Enabled":true},"NV_ACStateOnError":false,"NV_ErrorHistory":[{"Code":"E0","Description":"No Error","Severity":"No Error","Time":"Thu Aug 4 15:53:21 2022"},{"Code":"E52","Description":"Communication Error - between Indoor and Master Wall Controller","Severity":"Stop","Time":"Thu Aug 4 15:53:06 2022"},{"Code":"E0","Description":"No Error","Severity":"No Error","Time":"Sat Jan 8 23:47:20 2022"},{"Code":"E15","Description":"Inverter Driver no communication or in Inverter Driver start-up","Severity":"Warning","Time":"Sat Jan 8 23:45:34 2022"},{"Code":"E0","Description":"No Error","Severity":"No Error","Time":"Sat Jan 8 23:45:19 2022"}],"NV_LastZoneCheck":"Thu Aug 4 2022","Overrides":{"Compressor_capacity":100,"Enabled":false,"Fan":"HIGH","LockOut":false,"Mode":"HEAT"},"SelfLearn":{"Error":0,"FanSpeed":653,"Progress":0,"Zones_bitmask":255},"Task":0},"SystemStatus":{"RequiredZoneFirmware":"31"},"UserAirconSettings":{"AwayMode":false,"EnabledZones":[false,false,false,false,true,false,false,false],"FanMode":"AUTO","Mode":"HEAT","NV_SavedZoneState":[false,false,false,false,true,false,false,false],"QuietMode":false,"TemperatureSetpoint_Cool_oC":23,"TemperatureSetpoint_Heat_oC":21,"isFastHeating":false,"isOn":true}}}

**Comment by jxg81** [comment]
Thanks for sending this through - can see the issue clearly and shouldn't be too much hassle to address.
I guess Actron must have updated the zone sensor hardware - my system is about 6months old. I also have sensors (not controllers) and they are reporting the humidity.

**Comment by lanebrain** [comment]
Cool - I just got these sensors 2 weeks ago they have been back ordered so my system just got fully installed this week.

-Brian

**Comment by jxg81** [comment]
Hey @lanebrain. I have just published a beta build to npm. It seems to be running fine for me with the changes, but would be great if you could give it a try and let me know.
Because its published as a beta you will need to manually select it within Homebridge. If you simply open the homebridge webUI, browse to the plugins section, you will see a little spanner icon on the bottom left of the actron-que plugin tile.  Simply click this and select 'install alternate version' and select the beta release from the drop down. Refer to the attached screenshot - and please let me know if you have any trouble with install or operation.
![alternate-version](https://user-images.githubusercontent.com/48175613/183056327-a0468237-7b42-460f-812f-61b9a66bcd9f.jpg)

**Comment by lanebrain** [comment]
Thanks Julian for the quick turnaround.  I installed the beta and it seems to be working fine for me as well.  I also no longer see the constant warnings in the logs, so nice work.

I do still see the humidity sensor in HomeKit - however it is always just shows 0% which is fine.  Maybe when you have some time, an option in settings or a parameter exposed in the config to just disable trying to read it so they won’t appear in the home app at all.  I have Eve room sensors in all my zones already and they report temp / humidity as well.   

I thought maybe I could hide them from the Homebridge accessories page, but when I do that, it doesn’t seem to actually hide them from the Home app.

Thanks again!

-Brian

**Comment by jxg81** [comment]
Hey  Brian,

Did you try clearing the accessory cache Homebridge? I believe the devices should not get recreated, but may still be there because of they are still in your cache from the old version.
You can find options for clearing the accessory cache on the settings page of the Homebridge webUI.
Let me know if you need any help with this. Would be great to know if this clears out the unwanted items

**Comment by lanebrain** [comment]
Perfect!  I went in and cleared each zone one by one from the cache and that sorted it!  

Thanks for the tip!  I no longer see the Actron humidity sensors anymore so that’s great!

Cheers!

-Brian

**Comment by jxg81** [comment]
Excellent - thanks for confirming. I have made a couple of extra enhancements while i was tinkering about. Specifically i have improved the responsiveness of device updates in homekit and also updated so that the heater/cooler will show as idle when target temp is hit and the fan stops running. Im just confirming i havent broken anything over the next day or so and will publish an update at the end of the weekend.

**Comment by lanebrain** [comment]
Sounds good!  I look forward to the updated release.

Cheers and have a great weekend.

-Brian
